server {
    listen 80;
    server_name localhost;

    # Where Nginx should look for the files
    root /usr/share/nginx/html;
    index index.html;

    # The magic routing block
    location / {
        # 1. Try to find the exact file ($uri)
        # 2. Try to find a folder with that name ($uri/)
        # 3. If both fail, route the request back to index.html
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }
}
